name: prompt_generator
description: Generate Project code for Claude, ChatGPT, Gemini, Grok and others AI
version: 1.0.1
repository: https://github.com/abbos2101/prompt_generator
homepage: https://www.linkedin.com/in/abbos2101/
topics: [ ai, generator, chatgpt, claude, grok]
funding: [ https://github.com/sponsors/abbos2101 ]

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  yaml: ^3.1.3

dev_dependencies:
  flutter_lints: ^6.0.0